name: App Deploy Pipeline

on: 
  workflow_run:
    workflows: [ "Terraform Infra Pipeline" ]
    types:
      - completed
  workflow_dispatch:
  
env: 
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: terraform-monitoring-on-eks-eks-cluster
  ECR_REPO_NAME: terraform-monitoring-on-eks-ecr-repository
  TAG: latest
  ACCOUNT_ID: "891062950211"

jobs:
  deploy:
    name: Deploy to EKS 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo 
        uses: actions/checkout@v3

      - name: Login to ECR 
        run: |
          aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and Push docker image
        run: |
          docker build -t 891062950211.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPO_NAME:$TAG ./app/frontend/
          docker push 891062950211.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPO_NAME:$TAG

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region us-east-1

      - name: Deploy to EKS 
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml