name: App Deploy Pipeline

on: 
  workflow_run:
    workflows: [ "Terraform Infra Pipeline-in" ]
    types:
      - completed
  workflow_dispatch:
  
env: 
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: terraform-eks-microservices-ci-cd-eks-cluster
  ECR_REPO_NAME: terraform-eks-microserivce-ci-cd-ecr-repo
  TAG: latest
  ACCOUNT_ID: 891062950211

jobs:
  deploy:
    name: Deploy to EKS 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo 
        uses: actions/checkout@v3

      - name: Login to ECR 
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build and Push docker image
        run: |
          docker build -t $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$TAG ./app
          docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$TAG

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Deploy to EKS 
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml