name: App Deploy Pipeline

on: 
  workflow_run:
    workflows: [ "Terraform Infra Pipeline" ]
    types:
      - completed
  workflow_dispatch:
  
env: 
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: terraform-monitoring-on-eks-eks-cluster
  ECR_REPO_NAME: terraform-monitoring-on-eks-ecr-repository
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TAG: latest
  ACCOUNT_ID: "891062950211"

jobs:
  deploy:
    name: Deploy to EKS 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo 
        uses: actions/checkout@v3

      - name: Login to ECR 
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build and Push docker image- Frontend Image
        run: |
          docker build -t $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$TAG-frontend ./app/frontend/
          docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$TAG-frontend

      - name: Build and Push docker image- Backend Image
        run: |
          docker build -t $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$TAG-backend ./app/backend/
          docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$TAG-backend

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
          # test

      - name: Deploy to EKS 
        run: |
          kubectl apply -f ./app/database/
          kubectl apply -f ./app/frontend/k8s/
          kubectl apply -f ./app/backend/k8s/