name: Terraform Infra Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  S3_BUCKET_NAME: terraform-monitoring-on-eks-tfstate-bucket
  DYNAMODB_LOCK_TABLE: terraform-state-lock-table

jobs:
  terraform:
    name: Provision Infra 
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Repo 
        uses: actions/checkout@v3

      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v3
      
      - name: Ensure backend bucket exists
        run: |
          aws s3api head-bucket --bucket $S3_BUCKET_NAME || \
          aws s3api create-bucket --bucket $S3_BUCKET_NAME --region $AWS_REGION

      - name: Ensure dynamodb table exist
        run: |
          aws dynamodb describe-table --table-name $DYNAMODB_LOCK_TABLE || \
          aws dynamodb create-table \
            --table-name $DYNAMODB_LOCK_TABLE \
            --attribute-definitions AttributeName=LockID,AttributeType=S \
            --key-schema AttributeName=LockID,KeyType=HASH \
            --billing-mode PAY_PER_REQUEST

      - name: Terraform Init 
        working-directory: environments/dev 
        run: terraform init -input=false

      - name: Terraform Format
        working-directory: environments/dev
        run: terraform fmt -recursive

      - name: Terraform Plan
        working-directory: environments/dev
        run: terraform plan 
      
      # - name: Terraform Apply 
      #   working-directory: environments/dev
      #   run: terraform apply --auto-approve

      
      - name: Terraform Destroy 
        working-directory: environments/dev
        run: terraform destroy --auto-approve